export interface DummyComplaint {
  id: string;
  title: string;
  description: string;
  date: string;
  location: string;
  status: 'PENDING' | 'IN PROGRESS' | 'RESOLVED';
  category: string;
  urgencyCount: number;
  urgencyLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  evidence: string; // Description of evidence
  image: string; // Evidence picture
  color: string;
  icon: string;
  lat: number;
  lng: number;
}

export const dummyComplaints: DummyComplaint[] = [
  {
    id: "1",
    title: "Broken Main Pipe",
    description: "Significant water leakage on Avenue 1 near the mosque. Water level rising on sidewalk.",
    date: "Oct 24, 2023",
    location: "Avenue 1, Mirpur DOHS",
    status: "PENDING",
    category: "Water Supply",
    urgencyCount: 14,
    urgencyLevel: "HIGH",
    evidence: "Photo of main pipe water bursting onto public sidewalk near Mosque entrance.",
    color: "#F87171",
    icon: "water-outline",
    lat: 23.8385,
    lng: 90.3685,
    image: "https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "2",
    title: "Major Pothole",
    description: "Deep pothole causing traffic hazards near the central park. Requires urgent asphalt resurfacing.",
    date: "Oct 21, 2023",
    location: "Park Area, Mirpur DOHS",
    status: "RESOLVED",
    category: "Roads & Traffic",
    urgencyCount: 8,
    urgencyLevel: "MEDIUM",
    evidence: "Photo showing 8-inch deep crater on main thoroughfare.",
    color: "#60A5FA",
    icon: "construct-outline",
    lat: 23.8360,
    lng: 90.3705,
    image: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "3",
    title: "Street Light Failure",
    description: "Three consecutive lamps are out, making Avenue 3 pitch dark at night. Safety hazard for pedestrians.",
    date: "Oct 19, 2023",
    location: "Avenue 3, Mirpur DOHS",
    status: "IN PROGRESS",
    category: "Streetlights",
    urgencyCount: 19,
    urgencyLevel: "HIGH",
    evidence: "Night photo showing dark street section between poles #12 and #15.",
    color: "#C67B00",
    icon: "bulb-outline",
    lat: 23.8375,
    lng: 90.3690,
    image: "https://images.unsplash.com/photo-1513222588078-d5e6ebac17f3?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "4",
    title: "Garbage Overflow",
    description: "The main garbage bin near the community center is overflowing into the street creating foul odor.",
    date: "Oct 26, 2023",
    location: "Community Center, Mirpur DOHS",
    status: "PENDING",
    category: "Waste Management",
    urgencyCount: 25,
    urgencyLevel: "CRITICAL",
    evidence: "Photo of overflowing dumpster and uncollected waste bags.",
    color: "#F87171",
    icon: "trash-outline",
    lat: 23.8390,
    lng: 90.3675,
    image: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "5",
    title: "Broken Swing",
    description: "One of the chain swings in the children's park has snapped and has sharp metallic edges exposed.",
    date: "Oct 27, 2023",
    location: "Children's Park, Mirpur DOHS",
    status: "IN PROGRESS",
    category: "Parks & Recreation",
    urgencyCount: 6,
    urgencyLevel: "MEDIUM",
    evidence: "Photo of broken swing set chain.",
    color: "#C67B00",
    icon: "bicycle-outline",
    lat: 23.8365,
    lng: 90.3710,
    image: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "6",
    title: "Illegal Parking",
    description: "Multiple commercial vehicles parked illegally on Avenue 5, completely blocking pedestrian walkway.",
    date: "Oct 28, 2023",
    location: "Avenue 5, Mirpur DOHS",
    status: "RESOLVED",
    category: "Roads & Traffic",
    urgencyCount: 11,
    urgencyLevel: "LOW",
    evidence: "Photo of license plates and blocked sidewalk.",
    color: "#60A5FA",
    icon: "car-outline",
    lat: 23.8380,
    lng: 90.3660,
    image: "https://images.unsplash.com/photo-1510442650500-93217e634e4c?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "7",
    title: "Fallen Tree Branch",
    description: "A large tree branch fell down during yesterday's rainstorm, blocking half of Avenue 2.",
    date: "Oct 29, 2023",
    location: "Avenue 2, Mirpur DOHS",
    status: "PENDING",
    category: "Parks & Recreation",
    urgencyCount: 16,
    urgencyLevel: "HIGH",
    evidence: "Photo of fallen branch obstructing northbound lane.",
    color: "#F87171",
    icon: "leaf-outline",
    lat: 23.8355,
    lng: 90.3695,
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "8",
    title: "Stray Dogs Aggression",
    description: "A pack of stray dogs has been chasing school children and residents near Avenue 4 corner.",
    date: "Oct 30, 2023",
    location: "Avenue 4, Mirpur DOHS",
    status: "IN PROGRESS",
    category: "Public Safety",
    urgencyCount: 22,
    urgencyLevel: "CRITICAL",
    evidence: "Resident video/photo report of dog pack aggregation area.",
    color: "#C67B00",
    icon: "paw-outline",
    lat: 23.8370,
    lng: 90.3680,
    image: "https://images.unsplash.com/photo-1548681528-6a5c45b66b42?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "9",
    title: "Open Drainage Manhole",
    description: "An open manhole without a protective cover is posing a severe hazard to night motorists.",
    date: "Oct 31, 2023",
    location: "Avenue 6, Mirpur DOHS",
    status: "PENDING",
    category: "Drainage System",
    urgencyCount: 30,
    urgencyLevel: "CRITICAL",
    evidence: "Photo of missing concrete manhole cover.",
    color: "#F87171",
    icon: "warning-outline",
    lat: 23.8395,
    lng: 90.3700,
    image: "https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&q=80&w=800",
  },
];
