export const dummyComplaints = [
  {
    id: "1",
    title: "Broken Main Pipe",
    description: "Significant water leakage on Avenue 1 near the mosque.",
    date: "Oct 24, 2023",
    location: "Avenue 1, Mirpur DOHS",
    status: "PENDING",
    color: "#F87171",
    icon: "water-outline",
    lat: 23.8385,
    lng: 90.3685,
  },
  {
    id: "2",
    title: "Major Pothole",
    description: "Deep pothole causing traffic hazards near the central park.",
    date: "Oct 21, 2023",
    location: "Park Area, Mirpur DOHS",
    status: "RESOLVED",
    color: "#60A5FA",
    icon: "construct-outline",
    lat: 23.8360,
    lng: 90.3705,
  },
  {
    id: "3",
    title: "Street Light Failure",
    description: "Three consecutive lamps are out, making Avenue 3 dark at night.",
    date: "Oct 19, 2023",
    location: "Avenue 3, Mirpur DOHS",
    status: "IN PROGRESS",
    color: "#C67B00",
    icon: "bulb-outline",
    lat: 23.8375,
    lng: 90.3690,
  },
];
