import { StyleSheet } from 'react-native';

export const palette = {
  teal: '#00475E',
  tealDark: '#003548',
  tealSoft: '#E3F1F4',
  amber: '#FFA454',
  amberSoft: '#FFF1E2',
  ink: '#17242E',
  body: '#4A5963',
  muted: '#71808A',
  white: '#FFFFFF',
  canvas: '#F5F8F9',
  line: '#DCE5E8',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.white },
  screen: { flex: 1, backgroundColor: palette.canvas },
  screenContent: { paddingBottom: 0 },
  fill: StyleSheet.absoluteFill,
  headerShell: {
    width: '100%',
    backgroundColor: palette.white,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
  },
  header: {
    width: '100%',
    maxWidth: 1180,
    minHeight: 76,
    alignSelf: 'center',
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 18,
  },
  brand: { flexDirection: 'row', alignItems: 'center', flexShrink: 1, gap: 10 },
  brandCopy: { flexShrink: 1 },
  logo: { width: 42, height: 42 },
  brandName: { color: palette.ink, fontSize: 17, fontWeight: '800', letterSpacing: -0.3 },
  brandTagline: { marginTop: 2, color: palette.muted, fontSize: 10, fontWeight: '500' },
  desktopNav: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  navLink: { minHeight: 40, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
  navLinkText: { color: palette.body, fontSize: 14, fontWeight: '700' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  signInButton: {
    minHeight: 42,
    paddingHorizontal: 17,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  signInText: { color: palette.teal, fontSize: 14, fontWeight: '800' },
  headerRegister: {
    minHeight: 44,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#E18431',
    borderRadius: 12,
    backgroundColor: palette.amber,
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 6px 14px rgba(144, 77, 0, 0.22)',
  },
  headerRegisterText: { color: palette.tealDark, fontSize: 14, fontWeight: '900' },
  mobileHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  mobileSignIn: {
    minHeight: 40,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#B9CDD3',
    borderRadius: 11,
    backgroundColor: palette.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobileSignInText: { color: palette.teal, fontSize: 13, fontWeight: '800' },
  mobileRegisterTop: {
    minHeight: 40,
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: '#E18431',
    borderRadius: 11,
    backgroundColor: palette.amber,
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 10px rgba(144, 77, 0, 0.16)',
  },
  mobileRegisterTopText: { color: palette.tealDark, fontSize: 13, fontWeight: '900' },
  menuButton: { width: 40, height: 40, borderRadius: 11, backgroundColor: palette.tealSoft, alignItems: 'center', justifyContent: 'center' },
  mobileMenu: { width: '100%', maxWidth: 1180, alignSelf: 'center', paddingHorizontal: 18, paddingBottom: 10 },
  mobileMenuLinks: { paddingVertical: 6, borderTopWidth: 1, borderTopColor: palette.line },
  pressed: { opacity: 0.72 },
  mainContent: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingTop: 12,
  },
  heroCarousel: {
    width: '100%',
    overflow: 'hidden',
    borderRadius: 24,
    backgroundColor: palette.tealDark,
    boxShadow: '0 18px 42px rgba(0, 53, 72, 0.18)',
  },
  heroSlide: { position: 'relative', justifyContent: 'flex-end', overflow: 'hidden' },
  heroShade: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(1, 20, 29, 0.66)' },
  heroCopy: { maxWidth: 680, paddingHorizontal: 22, paddingTop: 90, paddingBottom: 74 },
  heroCopyDesktop: { paddingHorizontal: 54, paddingBottom: 82 },
  eyebrow: {
    alignSelf: 'flex-start',
    marginBottom: 15,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.38)',
    borderRadius: 99,
    backgroundColor: 'rgba(0, 53, 72, 0.54)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  eyebrowText: { color: palette.white, fontSize: 11, fontWeight: '800', letterSpacing: 1.2 },
  heroTitle: { color: palette.white, fontSize: 38, lineHeight: 43, fontWeight: '900', letterSpacing: -1.35, textShadowColor: 'rgba(0, 0, 0, 0.35)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 5 },
  heroTitleDesktop: { fontSize: 56, lineHeight: 61, letterSpacing: -2 },
  heroDescription: {
    maxWidth: 570,
    marginTop: 17,
    color: 'rgba(255, 255, 255, 0.88)',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '500',
  },
  heroDescriptionDesktop: { fontSize: 18, lineHeight: 27 },
  heroActions: { marginTop: 25, flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  heroPrimary: {
    minHeight: 51,
    minWidth: 178,
    paddingHorizontal: 19,
    borderWidth: 1,
    borderColor: '#FFD0A2',
    borderRadius: 14,
    backgroundColor: '#FFB15D',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    boxShadow: '0 8px 18px rgba(0, 0, 0, 0.20)',
  },
  heroPrimaryText: { color: palette.tealDark, fontSize: 15, fontWeight: '900' },
  heroSecondary: {
    minHeight: 51,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  heroSecondaryText: { color: palette.white, fontSize: 15, fontWeight: '800' },
  carouselControls: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderRadius: 99,
    backgroundColor: 'rgba(0, 33, 45, 0.62)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  carouselDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: 'rgba(255, 255, 255, 0.46)' },
  carouselDotActive: { width: 24, backgroundColor: palette.amber },
  trustStrip: {
    marginHorizontal: 18,
    marginTop: -22,
    paddingVertical: 22,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 18,
    backgroundColor: palette.white,
    flexDirection: 'row',
    boxShadow: '0 12px 28px rgba(18, 56, 68, 0.10)',
  },
  trustStripStacked: { marginHorizontal: 10, paddingVertical: 6, flexDirection: 'column' },
  trustItem: { flex: 1, paddingHorizontal: 22, flexDirection: 'row', alignItems: 'center', gap: 12 },
  trustItemMobile: { width: '100%', paddingHorizontal: 15, paddingVertical: 14 },
  trustItemDivider: { borderRightWidth: 1, borderRightColor: palette.line },
  trustItemMobileDivider: { borderBottomWidth: 1, borderBottomColor: palette.line },
  trustIcon: { width: 44, height: 44, borderRadius: 13, backgroundColor: palette.tealSoft, alignItems: 'center', justifyContent: 'center' },
  trustCopy: { flex: 1 },
  trustTitle: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  trustDescription: { marginTop: 3, color: palette.muted, fontSize: 12, lineHeight: 17 },
  section: { paddingHorizontal: 6, paddingTop: 78 },
  sectionIntro: { maxWidth: 670 },
  sectionEyebrow: { marginBottom: 10, color: palette.teal, fontSize: 11, fontWeight: '900', letterSpacing: 1.45 },
  sectionTitle: { color: palette.ink, fontSize: 31, lineHeight: 38, fontWeight: '900', letterSpacing: -0.8 },
  sectionDescription: { marginTop: 11, color: palette.body, fontSize: 16, lineHeight: 24 },
  cardGrid: { marginTop: 28, flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  workflowCard: {
    minHeight: 228,
    padding: 20,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 18,
    backgroundColor: palette.white,
    boxShadow: '0 8px 22px rgba(18, 56, 68, 0.06)',
  },
  fourColumnCard: { width: '23.8%', flexGrow: 1 },
  threeColumnCard: { width: '31.8%', flexGrow: 1 },
  twoColumnCard: { width: '47%', flexGrow: 1 },
  oneColumnCard: { width: '100%' },
  workflowCardTop: { marginBottom: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  stepIcon: { width: 46, height: 46, borderRadius: 14, backgroundColor: palette.tealSoft, alignItems: 'center', justifyContent: 'center' },
  stepNumber: { color: '#B5C2C7', fontSize: 27, fontWeight: '900' },
  workflowTitle: { color: palette.ink, fontSize: 17, lineHeight: 22, fontWeight: '900' },
  workflowDescription: { marginTop: 9, color: palette.body, fontSize: 14, lineHeight: 21 },
  categorySection: { marginTop: 76, paddingHorizontal: 24, paddingVertical: 50, borderRadius: 24, backgroundColor: palette.tealSoft },
  categoryHeader: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-end', justifyContent: 'space-between', gap: 20 },
  textAction: { minHeight: 44, paddingHorizontal: 4, flexDirection: 'row', alignItems: 'center', gap: 8 },
  textActionLabel: { color: palette.teal, fontSize: 15, fontWeight: '900' },
  categoryGrid: { marginTop: 28, flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  categoryCard: {
    minWidth: 150,
    minHeight: 74,
    paddingHorizontal: 15,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#CDDFE4',
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
    flexGrow: 1,
    flexBasis: 170,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  categoryIcon: { width: 43, height: 43, borderRadius: 13, backgroundColor: palette.white, alignItems: 'center', justifyContent: 'center' },
  categoryLabel: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  storyGrid: { marginTop: 28, flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  storyCard: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 19,
    backgroundColor: palette.white,
    boxShadow: '0 8px 22px rgba(18, 56, 68, 0.07)',
  },
  storyImage: { width: '100%', height: 214 },
  storyContent: { padding: 17, flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  storyIndex: { width: 31, height: 31, borderRadius: 10, backgroundColor: palette.amberSoft, alignItems: 'center', justifyContent: 'center' },
  storyIndexText: { color: '#8A4B12', fontSize: 13, fontWeight: '900' },
  storyText: { flex: 1 },
  storyLabel: { color: palette.ink, fontSize: 16, fontWeight: '900' },
  storyDetail: { marginTop: 5, color: palette.muted, fontSize: 13, lineHeight: 19 },
  ctaSection: {
    marginTop: 78,
    marginBottom: 78,
    minHeight: 380,
    overflow: 'hidden',
    paddingHorizontal: 22,
    paddingVertical: 58,
    borderRadius: 25,
    backgroundColor: palette.teal,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaGlow: { position: 'absolute', top: -90, right: -40, width: 280, height: 280, borderRadius: 140, backgroundColor: 'rgba(255, 164, 84, 0.17)' },
  ctaIcon: { width: 52, height: 52, marginBottom: 19, borderRadius: 16, backgroundColor: palette.amber, alignItems: 'center', justifyContent: 'center' },
  ctaEyebrow: { color: palette.amber, fontSize: 11, fontWeight: '900', letterSpacing: 1.4, textAlign: 'center' },
  ctaTitle: { maxWidth: 680, marginTop: 11, color: palette.white, fontSize: 34, lineHeight: 40, fontWeight: '900', letterSpacing: -1, textAlign: 'center' },
  ctaDescription: { maxWidth: 560, marginTop: 13, color: 'rgba(255, 255, 255, 0.78)', fontSize: 15, lineHeight: 23, textAlign: 'center' },
  ctaActions: { marginTop: 27, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 10 },
  ctaPrimary: {
    minHeight: 50,
    paddingHorizontal: 20,
    borderRadius: 14,
    backgroundColor: palette.amber,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  ctaPrimaryText: { color: palette.tealDark, fontSize: 14, fontWeight: '900' },
  ctaSecondary: { minHeight: 50, paddingHorizontal: 20, borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.4)', borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  ctaSecondaryText: { color: palette.white, fontSize: 14, fontWeight: '800' },
  footer: {
    width: '100%',
    paddingHorizontal: 22,
    paddingVertical: 31,
    borderTopWidth: 1,
    borderTopColor: palette.line,
    backgroundColor: palette.white,
    alignItems: 'center',
    gap: 22,
  },
  footerBrand: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  footerLogo: { width: 38, height: 38 },
  footerBrandName: { color: palette.ink, fontSize: 15, fontWeight: '900' },
  footerBrandLine: { marginTop: 2, color: palette.muted, fontSize: 11 },
  footerNav: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 7 },
  copyright: { color: palette.muted, fontSize: 11, fontWeight: '600' },
});
