export type AuthorityActivityType = 'Complaint' | 'Report' | 'Account';

export const authorityActivityLog = [
  {
    id: 'ACT-701',
    type: 'Complaint' as AuthorityActivityType,
    title: 'Started work on CMP-1042',
    detail: 'Added a work plan, budget, and deadline for the streetlight repair.',
    time: 'Today, 9:40 AM',
    icon: 'construct-outline' as const,
    color: '#C67B00',
    background: '#FFF7E8',
  },
  {
    id: 'ACT-699',
    type: 'Complaint' as AuthorityActivityType,
    title: 'Reviewed CMP-1048',
    detail: 'Opened the assigned drainage complaint and verified resident evidence.',
    time: 'Today, 8:55 AM',
    icon: 'document-text-outline' as const,
    color: '#3B82F6',
    background: '#EEF6FF',
  },
  {
    id: 'ACT-694',
    type: 'Report' as AuthorityActivityType,
    title: 'Generated authority analytics report',
    detail: 'Created the 30-day performance and complaint distribution report.',
    time: 'Yesterday, 4:15 PM',
    icon: 'bar-chart-outline' as const,
    color: '#7C6BC4',
    background: '#F2EFFE',
  },
  {
    id: 'ACT-688',
    type: 'Complaint' as AuthorityActivityType,
    title: 'Resolved CMP-1027',
    detail: 'Closed the missed garbage collection complaint after final inspection.',
    time: '19 Jul, 5:30 PM',
    icon: 'checkmark-done-outline' as const,
    color: '#16845B',
    background: '#EAF8F1',
  },
  {
    id: 'ACT-681',
    type: 'Account' as AuthorityActivityType,
    title: 'Signed in to authority portal',
    detail: 'Successful account access from the registered device.',
    time: '19 Jul, 8:02 AM',
    icon: 'log-in-outline' as const,
    color: '#23435D',
    background: '#E8EEF2',
  },
] as const;
